spring.application.name=notification-service
# ==============================
# MySQL Database
# ==============================

spring.datasource.url=jdbc:mysql://localhost:3306/?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=Root@1234

# ==============================
# JPA / Hibernate
# ==============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# Server
# ==============================

server.port=8084
#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${shubhambonde2054@gmail.com}
spring.mail.password=${fdzd uoah rkeh xxdy}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#sms 
twilio.account-sid=${AC70ea8015bd2245dc0e276a6f83675385}
twilio.auth-token=${22fdacdbf2a4fd9bf6734e3066ccb69}
twilio.phone-number=${TWILIO_PHONE_NUMBER}